apiVersion: inference.scaleway.m.upbound.io/v1alpha1
kind: Deployment
metadata:
  annotations:
    meta.upbound.io/example-id: inference/v1alpha1/deployment
  labels:
    testing.upbound.io/example-name: deployment
  name: deployment
  namespace: upbound-system
spec:
  forProvider:
    acceptEula: true
    name: tf-inference-deployment
    nodeType: L4
    publicEndpoint:
    - isEnabled: true
