apiVersion: k8s.scaleway.upbound.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    autohealing: true
    autoscaling: true
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    containerRuntime: containerd
    maxSize: 10
    minSize: 0
    nodeType: DEV1-M
    placementGroupId: 1267e3fd-a51c-49ed-ad12-857092ee3a3d
    size: 3

---

apiVersion: k8s.scaleway.upbound.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    cni: cilium
    version: 1.32.3
