apiVersion: datawarehouse.scaleway.m.upbound.io/v1alpha1
kind: Deployment
metadata:
  annotations:
    meta.upbound.io/example-id: datawarehouse/v1alpha1/deployment
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    cpuMax: 4
    cpuMin: 2
    name: my-datawarehouse
    passwordSecretRef:
      key: example-key
      name: example-secret
    ramPerCpu: 4
    replicaCount: 1
    version: v25
